Initial rewrite
JupiterOne/graph-okta pull request #124
Opened 2021-04-19 20:03 UTC by kevincasey1222

Hello @aiwilliams !

Here is the Okta rewrite, using the new SDK and the latest Okta client. Enjoy. :)

Kevin

2021-04-20 20:43 UTC, aiwilliams reviewed
Thanks @kevincasey1222 ! This is a lot simpler.

I'm starting to think it would be helpful in future transitions to keep entity converter code in the converters files, especially when there are tests for those converter functions.

2021-04-20 20:43 UTC, aiwilliams commented on src/initializeContext.ts
> -  });
Is anything still logging `application` or `user` properties so that these serializers would still be needed?

2021-04-20 20:43 UTC, aiwilliams commented on src/invocationValidator.test.ts
> -test("should throw if okta configuration is not found", async () => {
Related to other comments about adding back some validation of the config, some of these tests seems useful.

2021-04-21 16:36 UTC, kevincasey1222 commented on package.json
> +  "version": "0.0.0",
Done. Sorry I missed that - first time doing a rewrite. :)

2021-04-21 16:41 UTC, kevincasey1222 commented on jest.config.js
> +require('dotenv').config({ path: path.resolve(__dirname, './.env') });
Right. Done.

2021-04-21 16:41 UTC, kevincasey1222 commented on docs/jupiterone.md
> +# Integration with JupiterOne
Cool. Did it.

2021-04-21 16:48 UTC, kevincasey1222 commented on src/util/getOktaAccountInfo.ts
> +  config?: object;
This was actually an unintended change. Not sure what happened here. But IntegrationInstance<IntegrationConfig> actually needs a lot more properties to be valid.

2021-04-21 16:49 UTC, kevincasey1222 commented on src/steps/account.ts
> +        },
I like it. Done.

2021-04-21 17:00 UTC, kevincasey1222 commented on src/client.ts
> +      await this.oktaClient.listGroups().each((e) => {});
No, that's good. Done.

2021-04-21 22:45 UTC, kevincasey1222 commented on src/config.ts
> +}
Added these in.

2021-04-21 22:47 UTC, kevincasey1222 commented on src/util/convertCredentialEmails.ts
> +export function convertCredentialEmails(credentials?: OktaUserCredentials) {
Moved the PII delete to right after we use this function.

2021-04-22 17:13 UTC, kevincasey1222 commented on src/steps/access.ts
> +    await apiClient.iterateFactorsForUser(user, async (factor) => {
Okay, this is now in its own step. Groups are also in their own step.

2021-04-23 16:24 UTC, kevincasey1222 commented
Hello @aiwilliams ! Converters are back in, as are the entity converter tests. I see the PR now needs one of you guys to approve running the workflow, but it tested solidly on my local machine, so it should be good. This PR should be much easier to review now, because there are less changes from the JupiterOne:master than before.

Per our conversation yesterday, I still need to research how we want to handle HTTP status 500s, and to verify that 403s and 404s are being handled correctly (our belief is that they are). But those will be small changes if changes are needed.

--Kevin

2021-04-26 21:38 UTC, aiwilliams requested changes
I've done some things to execute the integration locally, and have almost got to a point where I can do a comparison of the old data with the new. In the meantime, this patch needs to be added to this PR, would you mind doing that @kevincasey1222? I've made some other comments as well. We're getting so close!

```diff
diff --git a/.gitignore b/.gitignore
index dcc15f1..3fabd7a 100644
--- a/.gitignore
+++ b/.gitignore
@@ -1,7 +1,6 @@
 node_modules/
-build/
-coverage/
 dist/
-yarn-error.log
-.env
-.eslintcache
\ No newline at end of file
+.j1-integration/
+.env*
+.eslintcache
+tsconfig.tsbuildinfo
diff --git a/src/converters/group.ts b/src/converters/group.ts
index 3935d33..33c831e 100644
--- a/src/converters/group.ts
+++ b/src/converters/group.ts
@@ -55,7 +55,7 @@ export function createUserGroupEntity(
     objectClass,
     type,
     name: profileName,
-    description: profileDescription,
+    description: profileDescription ? profileDescription : undefined,
   };
 
   return entity;
diff --git a/src/steps/applications.ts b/src/steps/applications.ts
index 1b2eb99..d897b9f 100644
--- a/src/steps/applications.ts
+++ b/src/steps/applications.ts
@@ -158,6 +158,18 @@ export const applicationSteps: IntegrationStep<IntegrationConfig>[] = [
         sourceType: 'okta_user',
         targetType: APPLICATION_ENTITY_TYPE,
       },
+      {
+        _type: USER_IAM_ROLE_RELATIONSHIP_TYPE,
+        _class: RelationshipClass.ASSIGNED,
+        sourceType: 'okta_user',
+        targetType: 'aws_iam_role',
+      },
+      {
+        _type: GROUP_IAM_ROLE_RELATIONSHIP_TYPE,
+        _class: RelationshipClass.ASSIGNED,
+        sourceType: 'okta_user_group',
+        targetType: 'aws_iam_role',
+      },
     ],
     dependsOn: ['fetch-groups'],
     executionHandler: fetchApplications,
diff --git a/src/types/entities.ts b/src/types/entities.ts
index 436b4c7..b0d4e5e 100644
--- a/src/types/entities.ts
+++ b/src/types/entities.ts
@@ -65,7 +65,7 @@ export interface StandardizedOktaUserGroup extends Entity {
   objectClass?: string[];
   type: string;
   name: string;
-  description: string;
+  description?: string;
 }
 
 export interface StandardizedOktaApplication extends Entity {
```

2021-04-26 22:10 UTC, kevincasey1222 commented on src/converters/group.test.ts
> -describe('creating group entity differently', () => {
Despite the name of the test, what the code actually tested was the synchronizer's creation of the `group HAS user` relationship, visible on [line 246](https://github.com/JupiterOne/graph-okta/blob/master/src/converters/group.test.ts) in the old file. Since we are depending on the SDK to do that now with `createDirectRelationship`, we don't need that test here.

2021-04-26 22:16 UTC, kevincasey1222 commented
The patch updates are applied. Also, Erkang's change from PR 125 is applied in a slightly different way.

2021-04-26 22:18 UTC, kevincasey1222 commented on src/converters/group.test.ts
> +          name: 'name',
@aiwilliams, I'm getting this when I try that: ERROR Local: Step "Fetch Groups" failed to complete due to error. (errorCode="DUPLICATE_RAW_DATA_NAME", errorId="c5c44ced-e31b-41be-95b7-df3aa402a9e9", reason="Duplicate raw data name 'default'!")

Ideas?

2021-04-27 12:21 UTC, aiwilliams commented on src/converters/group.test.ts
> +          name: 'name',
This code is already providing the `"default"` raw data entry when it provides the `source: group`. The `assign`d value does not need the `_rawData` property, though it is possible to provide it, only entries should be in addition to the `"default"` entry that would come from `source: group`.

```ts
createIntegrationEntity({
        entityData: {
          source: group,
          assign: createUserGroupEntity(instance.config, group),
        },
      }),
```

I would recommend making `createUserGroupEntity(instance.config, group)` and let it call the `createIntegrationEntity()` function itself.

2021-04-27 16:30 UTC, kevincasey1222 commented
Hello @aiwilliams !

With these last commits, I have done all my remaining to-do items for this PR. It's ready for you to do your diff versus the old code and see what falls out. Of course, I'll be happy to make whatever updates are needed as a result of that.

Thanks!
Kevin

2021-06-15 02:20 UTC, aiwilliams commented
Work completed in #126

2021-06-15 02:20 UTC, closed without merging