Adding rules
JupiterOne/graph-okta pull request #138
Opened 2021-07-14 20:00 UTC by kevincasey1222

Hi @aiwilliams !

This rules ingestion should be good to go. It tests solidly. 

Note that this PR does not automatically label users as to whether they were added by a certain rule. That's a bit messier because the `.conditions` and `.actions` properties from the API are just text of Okta's custom scripting language. I would have to write a parser to properly interpret it, and testing it would be hard. I think we should leave it to customers to use J1QL to retrieve these properties from the ingested rules and do their own specific-use-case parsing to determine which of their users were added by rules.

But if you disagree, let me know and I'll put some energy into scoping a parser for Okta's rules scripting language.

Also, I rolled your PR#137 changes into this one. 

--Kevin

2021-07-14 20:01 UTC, kevincasey1222 commented
Maybe I should mention @mknoedel for review?

2021-07-14 21:54 UTC, aiwilliams requested changes
Thanks for driving this forward! It's great to get the rules ingested. I think we'll need to work out exactly how users will use J1QL to find users added by rules, to get the request fully closed.

2021-07-14 21:54 UTC, aiwilliams commented on CHANGELOG.md
> +## 2.1.0 - 2021-07-14
It's best to leave these version lines out of feature PRs. We'll create a PR for the versioned release, which will include this line, change to the `package.json` `version`, and a git tag. When this version PR is merged to master, the Github workflow will publish to NPM because of the tagged commit merging to master.

2021-07-14 21:54 UTC, aiwilliams commented on src/okta/types/rules.ts
> +  status: string; //example: "ACTIVE" or "INACTIVE"
Thanks for these examples! Are they the only two values? If so, this could be expressed as `type: 'group_rule' | 'policy_rule'`, etc.

2021-07-14 21:54 UTC, aiwilliams commented on docs/jupiterone.md
> +  to determine which users were added via rules.
What would this query look like? We can add a managed question.

2021-07-14 21:54 UTC, aiwilliams commented on src/steps/rules.ts
> +];
These should be moved to https://github.com/JupiterOne/graph-okta/blob/master/src/steps/constants.ts.

2021-07-14 21:54 UTC, aiwilliams commented on src/steps/rules.ts
> +            _class: 'Configuration',
This should use the constants moved to https://github.com/JupiterOne/graph-okta/blob/master/src/steps/constants.ts, such as `Entities.RULE._type` etc.

2021-07-15 17:15 UTC, kevincasey1222 commented on CHANGELOG.md
> +## 2.1.0 - 2021-07-14
Ah, okay, thanks for that insight. Removing this line.

2021-07-15 17:21 UTC, kevincasey1222 commented on src/okta/types/rules.ts
> +  status: string; //example: "ACTIVE" or "INACTIVE"
Good to know as an option. I actually don't have specific knowledge of the possibilities. Okta just provided an example object or two, but I didn't find a technical schema description.

2021-07-15 17:23 UTC, kevincasey1222 commented on docs/jupiterone.md
> +  to determine which users were added via rules.
I think I need help from you on answering that. Here's an example of the properties returned: 

`{
  "type": "group_rule",
  "id": "0pr3f7zMZZHPgUoWO0g4",
  "status": "INACTIVE",
  "name": "Engineers Group Rule",
  "created": "2016-12-01T14:40:04.000Z",
  "lastUpdated": "2016-12-01T14:40:04.000Z",
  "conditions": {
      "people": {
        "users": {
          "exclude": [
            "00u22w79JPMEeeuLr0g4"
          ]
        },
        "groups": {
          "exclude": []
        }
      },
      "expression": {
        "value": "user.role==\"Engineer\"",
        "type": "urn:okta:expression:1.0"
      }
    },
  "actions": {
    "assignUserToGroups": {
      "groupIds": [
        "00gjitX9HqABSoqTB0g3"
      ]
    }
  }
}`

2021-07-15 17:27 UTC, kevincasey1222 commented on docs/jupiterone.md
> +  to determine which users were added via rules.
As you can see, the `conditions` to activate the rule are expressed as a hierarchy of objects, but we don't have a map of all possibilities. The `actions` are similarly constructed, but again, we don't have a list of all possible actions. We could sorta guess with some research, or make lots of variations in the dev environment and re-derive the model, but it seems like it might not be worth it to J1. I feel like the kinds of customers that would use Rules and monitor them in the J1 graph would be able to observe the properties of their specific Rules entities and write scripts to parse on that - whereas us trying to right a general-case parser leads to the possibility of many bugs. Especially when I consider how to handle conflicting rules and resolving precedence.

2021-07-15 17:29 UTC, kevincasey1222 commented on docs/jupiterone.md
> +  to determine which users were added via rules.
That being said, I could totally start black-box testing the combinations of rules and developing an estimation of their modeling. I don't mind. Just saying that it's non-trivial, and asking whether the value is there.

2021-07-15 17:55 UTC, kevincasey1222 commented on docs/jupiterone.md
> +  to determine which users were added via rules.
If you want to research it more, checkout : https://dev-857255-admin.okta.com/admin/groups#rules
From there you can add a rule and see all the basic attributes that can be used. There are a few dozen user attributes that can be parsed, in terms of `equals`, `startsWith` or `contains`, or you can build rules based on group membership. 
But also, you can write arbitrary matching expression for rules with Okta Expression Language, https://developer.okta.com/docs/reference/okta-expression-language/, and I don't know how those get encoded in the JSON Rules object `conditions`.

2021-07-15 17:59 UTC, kevincasey1222 commented on docs/jupiterone.md
> +  to determine which users were added via rules.
tldr, I think covering all the possibilities is too gnarly for us, but a customer could look at their Rules objects in J1, interpret the conditions, and then write custom J1QL queries that find those users. That still wouldn't guarantee that all those users were added by the rule (ie. they could have been added manually before the rule), but that might be okay depending on the customer's use case.

2021-07-15 18:10 UTC, kevincasey1222 commented on src/steps/rules.ts
> +];
Got it. Done.

2021-07-15 18:10 UTC, kevincasey1222 commented on src/steps/rules.ts
> +            _class: 'Configuration',
Got it. Done.

2021-07-16 20:34 UTC, aiwilliams commented on docs/jupiterone.md
> +  to determine which users were added via rules.
This is great research, thanks @kevincasey1222 ! I agree that we don't need to go into all that for this PR, and we'll need to work out when it's worth investing in our own rules interpreter for this thing.

2021-07-16 20:59 UTC, aiwilliams approved these changes

2021-07-16 21:05 UTC, merged