INT-7445 Fix duplicate key on applications and groups relationship
JupiterOne/graph-okta pull request #219
Opened 2023-03-31 17:06 UTC by jroblesx

### Description
An error is generated while adding a group and application relationship, to mitigate the error I used `jobState.hasKey` to verify if exists before try to add an existing relationship.

2023-03-31 17:15 UTC, mishelashala requested changes

2023-03-31 17:15 UTC, mishelashala commented on src/steps/applications.ts
> +        const relationshipId = `${group.id}|assigned|${appEntity._key}`;
can we add a unit test and an abstraction for this?

```ts
const relationShipId = getRelationShipId(group.id, appEntity._key);
```

2023-04-07 16:24 UTC, ndowmon commented on src/steps/applications.ts
> +        const relationshipId = `${group.id}|assigned|${appEntity._key}`;
TBH, this doesn't seem like complex enough logic that it's worth unit testing/abstracting, in my opinion.

2023-04-07 19:09 UTC, ndowmon commented on src/steps/applications.ts
> +          logger,
```suggestion
      const relationship = createApplicationGroupRelationships(
            appEntity,
            group,
            createOnInvalidRoleFormatFunction(logger, {
              appId,
              groupId: group.id,
            }),
          )
```

2023-04-07 19:11 UTC, ndowmon commented on src/steps/applications.ts
> +        }
```suggestion
        for (const relationship of relationships) {
          if (!jobState.hasKey(relationship._key)) {
            await jobState.addRelationships(relationship)
          }

        }
```

2023-04-07 19:28 UTC, ndowmon commented on src/steps/applications.ts
> +        }
I would also consider adding a comment about _why_ multiple assignments are possible. 

E.g.

```ts
        /**
         * Multiple relationships for the same group can be encountered if the 
         * app has specific profiles associated. 
         * 
         * For example, the AWS Account Federation app has a profile that 
         * specifies "role". The same group could be assigned multiple roles, 
         * such as `Developer` and `DeveloperExternal`.
         * 
         *  {
         *    id: '00gc3frhdodo90K6Q4x7',
         *    lastUpdated: '2023-04-07T19:19:30.000Z',
         *    priority: 0,
         *    profile: { role: 'Developer' },
         *  }
         *  {
         *    id: '00gc3frhdodo90K6Q4x7',
         *    lastUpdated: '2023-04-07T19:19:30.000Z',
         *    priority: 1,
         *    profile: { role: 'DeveloperExternal' },
         *  }
         */
```

2023-04-17 22:09 UTC, jroblesx commented on src/steps/applications.ts
> +        }
Added!

2023-04-17 22:12 UTC, jroblesx commented on src/steps/applications.ts
> +        if (relationships && relationships.length) {
If clause removed

2023-04-18 13:10 UTC, ndowmon approved these changes

2023-04-18 13:20 UTC, closed without merging